### ISSUE TITLE
Characters after the Cursor

### ISSUE THREAD

**Issue by Grischabock** [WoltLab/editor#20]
When you write a text, after two or three words (spaces), a letter follows the cursor, which moves with you.

![Screenshot_20230404_222902_Firefox~2](https://user-images.githubusercontent.com/26699897/229913991-22938dbf-5294-4ae2-a637-e09f907cc7a0.png)

Phone: Samsung Galaxy S23 Ultra
Android: Version 13
Browser: Firefox 111.1.1

**Comment by TimWolla** [comment]
Does this also happen with an official CKEditor demo, e.g. here: https://ckeditor.com/ckeditor-5/demo/feature-rich/? What keyboard are you using?

**Comment by Grischabock** [comment]
I can't reproduce the problem in the linked CKEditor demo. Everything works as usual. I use the original Samsung keyboard.

**Comment by SoftCreatR** [comment]
> > I use the original Samsung keyboard.
> 
> Please provide a link to the Google Play Store entry of that keyboard.

We received reports from other customers as well. I'll try go get the required, technical information.

**Comment by SoftCreatR** [comment]
Samsung Smartphone J7 Max using the original vendor keyboard.

**Comment by dtdesign** [comment]
We’ve tested the behavior with SwiftKey, GBoard and even through voice input, but could not observe any issues. It was verified that typing, swiping, autocomplete and insertions in the middle of a word work just fine. Please understand that we cannot provide support for apps installed from unofficial sources for safety reasons.

In addition, it is very unlikely that this is caused by any modification on our end, because we do not modify the cursor behavior at all. The observed correct behavior suggest that this might be a general issue with the proprietary keyboard from Samsung and that occurs with CKEditor 5 in general. I suggest that you submit an issue to CKEditor and have them look into.
