### ISSUE TITLE
`[wsm]` BBCode not rendered into an image when editing

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/editor#47]
Specifically I noticed the issue for this variant `[wsm=1023,'medium','none'][/wsm]`.

**Comment by dtdesign** [comment]
I’m not sure if we really want to support this. Media inserted into the editor uses an actual image element which is preserved at all times.

The BBCode on the other hand can represent both an image and a regular file, therefore we cannot safely upcast these instances. The previous editor implementation performed an unconditional upcast which is incorrect for regular files.

These occurrences are most likely artifacts from WCF 2.0 which lacked an in-editor upcast and thus should not be a common issue. We should rather upcast these during the HTML input processing, so that this BBCode will no longer be used for images.
