### ISSUE TITLE
Make Plugin load available 

### ISSUE THREAD

**Issue by Cyperghost** [WoltLab/editor#92]
To be able to load custom CKEditor plugins, the bundle must export some modules. These can then be loaded via `window.CKEditor5.[ModuleName]`.

For simplicity this could be done by adding this to `app.ts`
```TS
import * as Core from "@ckeditor/ckeditor5-core";
import * as Ui from "@ckeditor/ckeditor5-ui";
...
export {Core, Ui};
```

Developers can then add to `configuration.extraPlugins` their plugins.

These plugins can be created as follows:
```TS

class TestPlugin extends window.CKEditor5.Core.Plugin {
	static get pluginName() {
		return "TestPlugin";
	}

	init(): void {
		...
	}
}
```

However, it should be noted that the bundle "ckeditor5-bundle" is already loaded at the time of loading this module. Alternatively, a helper function can be used to ensure that this is loaded:

```TS
export default async function loadPlugin() {
	await import("ckeditor5-bundle");

	return class TestPlugin extends window.CKEditor5.Core.Plugin {
		static get pluginName() {
			return "TestPlugin";
		}

		init(): void {
			...
		}
	}
}
```

If the bundle is exported as amd-module, access to the variable window can also be omitted here.

**Comment by dtdesign** [comment]
@Cyperghost I’ve went a slightly different route because I wanted to verify that the imported modules within the bundle stay in sync with the export. In addition, I have includes the modules in the `setupConfiguration()` event in the core to allow the synchronous access to all exports. Your attempt did not work because of race conditions caused by the asynchronous execution of callbacks.

For now the integration in the core lacks typings for the modules, but I’ve set them to `any` for the time being to make it somewhat easier to try it out. It did work in my tests and I would like to verify with you if you see any problems with it. We’ll add the proper typings later once the PRs have been finialized.

In order to try this out you will need both https://github.com/WoltLab/editor/pull/95 and https://github.com/WoltLab/WCF/pull/5652

**Comment by Cyperghost** [comment]
The result is similar to what I had prepared and seems to do what is required to create plugins.
